### ISSUE TITLE
Add support to register any library on readthedocs

### ISSUE THREAD

**Issue by jcohen28** [leos/DocsVersionRedirector#1]
Thanks for creating this simple but helpful app. It would be even more useful to be able to dynamically register any library that is documented via readthedocs.

**Comment by leos** [comment]
Note to self: https://readthedocs.org/projects/django-reversion/versions/

**Comment by leos** [comment]
Fixed in https://github.com/leos/DocsVersionRedirector/commit/3f1008c98dc38595046da23e55ee4463d106728b - Pending review right now

![image](https://user-images.githubusercontent.com/214370/82162182-88f8fe80-9870-11ea-8f65-9eb5e831b457.png)
